/******************
 * OpenTSC Header *
 * Replace me     *
******************/
#pragma once

#include "common/types.h"
#include "common/math/e_vec3.h"

#include "ESRC/camera.h"
#include "ESRC/gamestate.h"

struct EGlobal {
	EGameStateId _curGameState;
	float _EHouse_levelrad;
	float _global_house_offx;
	float _global_house_offy;
	bool _bGamePaused;
	bool _bForceCtrl2Connect;
	u8 _VanityMirrorState;
	u8 _UnlockDialogState;
	u8 _HighScoreDialogState;
	u32 m_nCreditMode;
	//ERLevel *_pNeighborhoodTerrain;
	//cXPerson *_pSelectedSims[2];
	//ESimsCursor *_pCursor[2];
	//EHouse *_pCurHouse;
	//ELights *_pCurLights;
	int _nCurLights;
	int m_renderPass;
	ESimsCam *_pCurCam;
    /*
	EPanel *_pPanel;
	EWardrobeMenu *_pWardrobe;
	EVanityMirrorMenu *_pVanityMirror;
	FloorSet *_pFloorSet;
	WallSet *_pWallSet;
	FenceSet *_pFenceSet;
	EUnlockDialog *_pUnlockDialog;
	EHighScoreDialog *_pHighScoreDialog;
	ERQuickdata *m_pUiData;
	ERQuickdata *m_pSpriteIdToResId;
	ERQuickdata *m_pTileData;
	ERQuickdata *m_waveDataTable;
	ERShader *m_pWhiteShader;
	ERShader *m_pBlackShader;
	ERFont *m_pFont;
	ERFont *m_pFontShadowed;
	EDialog *m_pDialog;
	E2PDialog *m_p2PDialog[2];
	EMessageDialog *m_pMessDialogs[2];
	Controllpad *m_pCtrlPad;
	ESpriteRenderMan *m_pSpriteMan;
	ERDataset *m_pDataset;
	EPictureInPicture *m_pPiP;
	EVibrate *m_pVibrate;
	ECheats *m_pCheats;
	ESimsMemCard *m_pMemCard;
	OptionsRecon *m_pOptionsRecon;*/
	bool m_bCtrl2Detected;
	int m_whichPlayerPaused;
	float m_vCameraRotDegrees;
	//ECheatVariables Cheats;
	int m_FamilyToMoveIn;
	u16 m_nUnlockBitField;
	u8 ChallengeModeHouseNum;
	bool m_bGotoNeighborhoodMode;
	bool m_bGotoStartMode;
	bool m_bUseCurrentNeighborhood;
	int m_NeighborhoodHouseNum;
	bool m_bSetNeighborhoodAsStoryMode;
	bool m_bStoryModeTransferHouses;
	bool m_bStoryModeDoSubstitutionOnTransfer;
	int m_StoryModeFamilyToMoveInBehind;
	int m_StoryModeMoveIntoHouseNum;
	bool m_bDisplayStoryModeTransitionScreen;
	c16 *m_pStoryModeTransitionText;
	//ERShader *m_pStoryModeTransitionShader;
	bool m_bStoryModeStart;
	bool m_bStoryModeWonGame;
	bool m_bDisplayGenericTransitionScreen;
	bool m_bDisplayingChallengeModeScreen;
	float m_GenTransitionLoadPercent;
	//ERShader *m_pGenericTransShader;
	bool m_bLanguageSelected;
	s32 m_nChallengePlayerNum;
	s32 m_nChallengeScore;
	s32 m_nChallengeComponent1;
	s32 m_nChallengeComponent2;
	s32 m_nChallengeComponent3;
	s32 m_nChallengeComponent4;
	s32 m_nUnlockCode;
	s32 m_nUnlockPersonId;
	s32 m_nUnlockGuid;
	bool m_bResetBackgroundColor;
	bool m_bListenToController;
	
	EGlobal();
	/* vtable[2] */ virtual bool TransformToScreen(/* s1 17 */ EVec3 &vWorldIn, /* s0 16 */ EVec2 &vScreenOut);
	/* vtable[3] */ virtual void Message(/* a1 5 */ void *pPram, /* a2 6 */ u32 messageId);
	///* vtable[4] */ virtual void GetCursorPosAsFtile(/* a1 5 */ FTilePt &pOut);
	///* vtable[5] */ virtual void DestroyInstance(/* s2 18 */ IBaseSimInstance **ppInstance);
	///* vtable[6] */ virtual void AllocInstance(/* s0 16 */ cXObject *pObject);
	///* vtable[7] */ virtual void AllocPersonInstance(/* s2 18 */ cXPerson *pPerson);
	///* vtable[8] */ virtual ESpriteRender* AllocSpriteRenderer(/* a1 5 */ cXObject *pSprite);
	///* vtable[9] */ virtual void FreeSpriteRenderer(/* a1 5 */ cXObject *pSprite);
	///* vtable[10] */ virtual void UpdateSpriteRenderer(/* a1 5 */ SpriteSlot *pSprite);
	///* vtable[11] */ virtual SpriteIdToResIdNode* ConvertSpriteIdToResId(/* s0 16 */ u32 id);
	///* vtable[12] */ virtual ECntrMdlLkupTable& GetCounterModelTable();
	///* vtable[13] */ virtual SAnimator* CreateAnimator();
	///* vtable[14] */ virtual void SetSelectedPerson(/* s4 20 */ u32 player, /* s3 19 */ cXPerson *newSelection, /* -0xb0(caller sp) */ bool reverse);
	/* vtable[15] */ virtual void AdvanceSelectedPerson(/* s6 22 */ u32 player);
	/* vtable[16] */ virtual void ReverseSelectedPerson(/* s7 23 */ u32 player);
	///* vtable[17] */ virtual void LoadSelectorData(/* a1 5 */ ObjSelector *sel, /* a2 6 */ bool bWait);
	///* vtable[18] */ virtual void UnloadSelectorData(/* a1 5 */ ObjSelector *sel);
	///* vtable[19] */ virtual bool CreateThumbnail(/* a1 5 */ ObjSelector *sel);
	/* vtable[20] */ virtual bool IsTwoPlayer();
	///* vtable[21] */ virtual bool IsObjectInUseByPlayer(/* a1 5 */ int which, /* s3 19 */ cXObject *pObject);
	/* vtable[22] */ virtual void RecalcFloor();
	/* vtable[23] */ virtual void RecalcWalls();
	/* vtable[24] */ virtual void RecalcObjects();
	/* vtable[25] */ virtual void RecalcHouse();
	///* vtable[26] */ virtual E3DWindow* GetWin();
	/* vtable[27] */ virtual void SelectWin(/* a1 5 */ ERC *prc);
	/* vtable[28] */ virtual ESimsCam* GetCam();
	/* vtable[29] */ virtual void SetCam(/* a1 5 */ ESimsCam *cam);
	///* vtable[30] */ virtual bool CreateWardrobe(/* s4 20 */ cXObject *pWorldObject, /* s0 16 */ cXPerson *pSim);
	///* vtable[31] */ virtual bool CreateVanityMirror(/* s4 20 */ cXObject *pWorldObject, /* s0 16 */ cXPerson *pSim);
	/* vtable[32] */ virtual void CreateUnlockDialog(/* a1 5 */ s32 guid);
	/* vtable[33] */ virtual void CreateNameEntry(/* s1 17 */ s32 nNewScoreIndex, /* s2 18 */ s32 nChallengePlayerNum, /* s3 19 */ s32 nChallengeScore);
	///* vtable[34] */ virtual void DoModelessMessage(/* v1 3 */ int player_id, /* s2 18 */ StackElem *elem, /* s3 19 */ DialogParam *dialogParam, /* a1 5 */ cXObject *pObj, /* t1 9 */ ObjSelector *pSel);
	/* vtable[35] */ virtual void SwapSelectedSims();
	void Reset();
	void SetDefaults();
	void LoadIntroRequirements();
	void LoadPreGlobalRequirements();
	void LoadNeigborhoodTerrain();
	void UnloadNeigborhoodTerrain();
	void SetCurHouse(/* s0 16 */ int house);
	void ClearCurHouse();
	//cXPerson* GetOtherPlayersSim(/* a1 5 */ u32 idx);
	void TransformToWorld(/* s2 18 */ EVec2 &vScreenIn, /* s1 17 */ EVec3 &vWorldOut);
	//void PlaceObjectInHouse(/* a1 5 */ cXObject *pOb);
	//void PickUpInHouseObject(/* a1 5 */ cXObject *pOb);
	c16* GetUiString(/* s0 16 */ char *pRef);
	c16* GetHelpString(/* s0 16 */ char *pRef);
	c16* GetCreateASimString(/* s0 16 */ char *pRef);
	c16* GetLiveModeMenuUIString(/* s0 16 */ char *pRef);
	c16* GetNeighborhoodModeString(/* s0 16 */ char *pRef);
	c16* GetMemCardUIString(/* s0 16 */ char *pRef);
	c16* GetCreditUIStrings(/* s0 16 */ char *pRef);
	c16* GetStoryModeIntroScreenText(/* s0 16 */ char *pRef);
	c16* GetStoryModeOutroScreenText(/* s0 16 */ char *pRef);
	u32 GetStoryModeIntroScreenShaderId(/* s0 16 */ char *pRef);
	u32 GetStoryModeOutroScreenShaderId(/* s0 16 */ char *pRef);
	c16* GetMainMenuUIString(/* s0 16 */ char *pRef);
	c16* GetUserCharacterArray(/* a1 5 */ u32 nIndex);
	u32 GetNumUserCharacters(/* a1 5 */ u32 nIndex);
	int ConvertUnicodeToShiftJIS(/* s0 16 */ c16 *pInput, /* s1 17 */ c16 *pOutput, /* s2 18 */ u32 bufferSize);
	//FloorSet& GetFloorSet();
	//WallSet& GetWallSet();
	//FenceSet& GetFenceSet();
	//int GetFloorIndex(/* a1 5 */ FloorTile *pTile);
	//int GetWallIndex(/* a1 5 */ WallTile *pTile);
	//int GetFenceIndex(/* a1 5 */ FenceData *pTile);
	/* vtable[36] */ virtual void BeginSaveGame();
	/* vtable[37] */ virtual void EndSaveGame();
	///* vtable[38] */ virtual bool CheckForZeroExtentOverride(/* s0 16 */ cXObject *pOb);
	/* vtable[39] */ virtual bool CheckForZeroExtentOverride();
	/* vtable[40] */ virtual s32 CallUnlockItems(/* a1 5 */ u32 code, /* a2 6 */ u32 nPersonId, /* a3 7 */ u16 *pnBitCode);
	/* vtable[41] */ virtual void CallTestUnlocked(/* a1 5 */ u32 code, /* a2 6 */ u16 *pnBitCode);
	/* vtable[42] */ virtual s32 CallNewScore(/* a1 5 */ s16 nPlayerNum, /* a2 6 */ s16 nScore, /* a3 7 */ s16 nComponent1, /* t0 8 */ s16 nComponent2, /* t1 9 */ s16 nComponent3, /* t2 10 */ s16 nComponent4);
	bool IsTransitionStoryMode();
	void HotSyncLighting();
	//ERShader* GetBuyBuildDPadUp();
	//ERShader* GetBuyBuildDPadDown();
	//ERShader* GetBuyBuildDPadLeft();
	//ERShader* GetBuyBuildDPadRight();
	//void AddParticleEffectToOrphanMan(/* s0 16 */ ERParticleType *pType, /* a2 6 */ EIParticleEmit *pEffect);
	void ProcessCheatCode(/* s4 20 */ c16 *String);
	bool IsChallangeMode();
	bool IsBuildHouseMode();
	void SetBackgroundColor();
	bool ListenForController();
	void SetListenFlag(/* a1 5 */ bool bFlag);
};

extern EGlobal _globals;
extern EVec2 _defULTextureCoord;
extern EVec2 _defLRTextureCoord;
extern EVec4 _vBlueBack;
extern EVec4 _WHITE;
extern EVec4 _BLACK;
extern EVec4 _YELLOW;
extern EVec4 _BLUE;
extern EVec4 _RED;
extern EVec4 _GREEN;
extern EVec4 _CYAN;
extern EVec4 _MAJENTA;
extern EVec4 _GREAY;
extern EVec4 _LT_GREAY;
extern EVec4 _DK_GREAY;
//extern EDialog *_pDialog;